name: sgENERATE
channels:
  - bioconda
  - defaults
dependencies:
  - samtools=1.9
  - bedtools=2.29.2
  - snakemake-minimal=5.13
  - pytest=5.4.2
  - pip=20.0.2
  - setuptools=52.0.0
  - pyvcf=0.6.8
  - bcbio-gff
