name: sgENERATE
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools==1.18
  - pip==23.3.1
  - snakemake-minimal==7.32.4
  - python==3.10.13
  - biopython==1.81 
  - matplotlib==3.8.2
  - pysam==0.22.0
  - upsetplot==0.8.0
  - pandas==2.1.3
  - matplotlib-venn==0.11.9
  - git

