name: sgENERATE
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - pip
  - snakemake-minimal
  - python
  - biopython
  - matplotlib
  - pysam
  - upsetplot
  - pandas
  - matplotlib-venn

