name: sgENERATE
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools
  - pip
  - snakemake-minimal
  - python = 3.8
  - biopython
  - matplotlib=3.8
  - pysam=0.18.0
  - upsetplot
  - pandas
  - matplotlib-venn

